<a href="https://colab.research.google.com/github/ivaibhavi17/Numpy_python/blob/main/numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
myarr = np.array([[1,2,3],[7,8,9]])
myarr

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
myarr.shape
myarr.dtype

dtype('int64')

Array creation:conversion from other python structures

In [ ]:
listarray = np.array([[1,4,5],[7,8,9],[5,6,0]])
listarray

array([[1, 4, 5],
       [7, 8, 9],
       [5, 6, 0]])

In [ ]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace = np.linspace(1,3,4)
lspace

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [ ]:
emp = np.empty((4,6))
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
emp = np.empty_like(lspace)
emp

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [ ]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
arr = np.arange(99)
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
x = ([1,2,3],[4,5,6],[7,1,0])
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr.sum(axis=0)

array([12,  8,  9])

In [ ]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
for item in arr.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
arr.ndim

2

In [ ]:
arr.nbytes

72

In [ ]:
one = np.array([1,3,4,634,2])
one.argmax()
one.argmin()
one.argsort()

array([0, 4, 1, 2, 3])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr.argmax()
arr.argmin()
arr.argsort()
arr.argmax(axis=0)
arr.argmax(axis=1)
arr.argsort(axis=0)


array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [ ]:
ar2 = ([[3,5,6],[6,9,5],[7,9,1]])

In [ ]:
arr +ar2

array([[ 4,  7,  9],
       [10, 14, 11],
       [14, 10,  1]])

In [ ]:
arr*ar2

array([[ 3, 10, 18],
       [24, 45, 30],
       [49,  9,  0]])

In [ ]:
np.sqrt(ar2)

array([[1.73205081, 2.23606798, 2.44948974],
       [2.44948974, 3.        , 2.23606798],
       [2.64575131, 3.        , 1.        ]])

In [ ]:
arr.sum()
arr.max()
arr.min()

np.int64(0)

In [ ]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [ ]:
np.count_nonzero(arr)

8

In [ ]:
import sys

In [ ]:
py_arr = [1,23,45,2]

In [ ]:
np_arr = np.array(py_arr)
sys.getsizeof(1)*len(py_arr)
np_arr.itemsize*np_arr.size

32